server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console  # Define explícitamente el path para acceder a la consola
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Para mostrar las sentencias SQL en los logs
    properties:
      hibernate:
        format_sql: true  # Para formatear la salida de las sentencias SQL
